version: "3.3"

services:
  product:
    container_name: product-service
    restart: always
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "database"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/grpc-poc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  database:
    container_name: database
    restart: always
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grpc-poc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
